# Generated by Django 4.1.2 on 2022-10-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_id', models.IntegerField(default=-1)),
                ('irrigation_time', models.DateTimeField()),
                ('irrigation_value', models.IntegerField()),
                ('irrigation_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_id', models.IntegerField(default=-1)),
                ('measurement_time', models.DateTimeField()),
                ('moisture_value', models.IntegerField()),
                ('temperature_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_pct', models.IntegerField(default=45)),
                ('stop_pct', models.IntegerField(default=55)),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('pot_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(default='Empty', max_length=50)),
                ('irrigation_last', models.DateTimeField(null=True)),
                ('irrigation_duration', models.IntegerField(default=-1)),
                ('irrigation_amount', models.IntegerField(default=-1)),
                ('measurement_last', models.DateTimeField(null=True)),
                ('moisture_value', models.IntegerField(default=-1)),
                ('temperature_value', models.IntegerField(default=-363)),
            ],
        ),
    ]
